const recipes = [
    {
        uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_b20815eac65ee2fa5f848f56c16056dd',
        label: 'Zuni-Inspired Grilled Chicken Salad',
        image: 'https://www.edamam.com/web-img/3ac/3accba1eeb5ac38d902d056050c05ead.jpg',
        images: {
            THUMBNAIL: {
                url: 'https://www.edamam.com/web-img/3ac/3accba1eeb5ac38d902d056050c05ead-s.jpg',
                width: 100,
                height: 100,
            },
            SMALL: {
                url: 'https://www.edamam.com/web-img/3ac/3accba1eeb5ac38d902d056050c05ead-m.jpg',
                width: 200,
                height: 200,
            },
            REGULAR: {
                url: 'https://www.edamam.com/web-img/3ac/3accba1eeb5ac38d902d056050c05ead.jpg',
                width: 300,
                height: 300,
            },
            LARGE: {
                url: 'https://www.edamam.com/web-img/3ac/3accba1eeb5ac38d902d056050c05ead-l.jpg',
                width: 600,
                height: 600,
            },
        },
        source: 'Food52',
        url: 'https://food52.com/recipes/82361-zuni-inspired-grilled-chicken-salad-recipe',
        shareAs:
            'http://www.edamam.com/recipe/zuni-inspired-grilled-chicken-salad-b20815eac65ee2fa5f848f56c16056dd/salad',
        yield: 4,
        dietLabels: ['Low-Carb'],
        healthLabels: [
            'Sugar-Conscious',
            'Keto-Friendly',
            'Paleo',
            'Dairy-Free',
            'Gluten-Free',
            'Wheat-Free',
            'Peanut-Free',
            'Tree-Nut-Free',
            'Soy-Free',
            'Fish-Free',
            'Shellfish-Free',
            'Pork-Free',
            'Red-Meat-Free',
            'Crustacean-Free',
            'Celery-Free',
            'Sesame-Free',
            'Lupine-Free',
            'Mollusk-Free',
            'Alcohol-Free',
            'Sulfite-Free',
            'Kosher',
        ],
        cautions: ['Sulfites'],
        ingredientLines: [
            '1 pound boneless, skinless chicken breasts',
            '3/4 teaspoon kosher salt, divided, plus more for salad',
            '1 tablespoon olive oil, plus more for salad',
            '1/4 cup aioli or 1/4 cup mayo + 1 small garlic clove, grated',
            'Zest and juice of 1 lemon, plus more for salad',
            'Your favorite greens and fresh herbs, for salad',
        ],
        ingredients: [
            {
                text: '1 pound boneless, skinless chicken breasts',
                quantity: 1,
                measure: 'pound',
                food: 'boneless, skinless chicken breasts',
                weight: 453.59237,
                foodCategory: 'Poultry',
                foodId: 'food_bdrxu94aj3x2djbpur8dhagfhkcn',
                image: 'https://www.edamam.com/food-img/da5/da510379d3650787338ca16fb69f4c94.jpg',
            },
            {
                text: '3/4 teaspoon kosher salt, divided, plus more for salad',
                quantity: 0.75,
                measure: 'teaspoon',
                food: 'kosher salt',
                weight: 3.6406250001846567,
                foodCategory: 'Condiments and sauces',
                foodId: 'food_a1vgrj1bs8rd1majvmd9ubz8ttkg',
                image: 'https://www.edamam.com/food-img/694/6943ea510918c6025795e8dc6e6eaaeb.jpg',
            },
            {
                text: '1 tablespoon olive oil, plus more for salad',
                quantity: 1,
                measure: 'tablespoon',
                food: 'olive oil',
                weight: 13.5,
                foodCategory: 'Oils',
                foodId: 'food_b1d1icuad3iktrbqby0hiagafaz7',
                image: 'https://www.edamam.com/food-img/4d6/4d651eaa8a353647746290c7a9b29d84.jpg',
            },
            {
                text: '1/4 cup aioli or 1/4 cup mayo + 1 small garlic clove, grated',
                quantity: 0.25,
                measure: 'cup',
                food: 'aioli',
                weight: 57.75,
                foodCategory: 'condiments and sauces',
                foodId: 'food_bu8t61zaplle7dbrzk81dbygq0qj',
                image: 'https://www.edamam.com/food-img/577/577308a0422357885c94cc9b5f1f1862.jpg',
            },
            {
                text: 'Zest and juice of 1 lemon, plus more for salad',
                quantity: 1,
                measure: '<unit>',
                food: 'lemon',
                weight: 58,
                foodCategory: 'fruit',
                foodId: 'food_a6uzc62astrxcgbtzyq59b6fncrr',
                image: 'https://www.edamam.com/food-img/70a/70acba3d4c734d7c70ef4efeed85dc8f.jpg',
            },
            {
                text: 'Your favorite greens and fresh herbs, for salad',
                quantity: 0,
                measure: null,
                food: 'fresh herbs',
                weight: 5.864829950001847,
                foodCategory: 'vegetables',
                foodId: 'food_b244pqdazw24zobr5vqu2bf0uid8',
                image: 'https://www.edamam.com/food-img/46a/46a132e96626d7989b4d6ed8c91f4da0.jpg',
            },
        ],
        calories: 1082.2121827820008,
        totalWeight: 590.8408973752244,
        totalTime: 20,
        cuisineType: ['british'],
        mealType: ['lunch/dinner'],
        dishType: ['salad', 'main course'],
        totalNutrients: {
            ENERC_KCAL: {
                label: 'Energy',
                quantity: 1082.2121827820008,
                unit: 'kcal',
            },
            FAT: {
                label: 'Fat',
                quantity: 70.07195225060502,
                unit: 'g',
            },
            FASAT: {
                label: 'Saturated',
                quantity: 11.089416618634003,
                unit: 'g',
            },
            FATRN: {
                label: 'Trans',
                quantity: 0.031751465900000005,
                unit: 'g',
            },
            FAMS: {
                label: 'Monounsaturated',
                quantity: 24.14441767765251,
                unit: 'g',
            },
            FAPU: {
                label: 'Polyunsaturated',
                quantity: 30.083229037938004,
                unit: 'g',
            },
            CHOCDF: {
                label: 'Carbs',
                quantity: 5.776843735835117,
                unit: 'g',
            },
            'CHOCDF.net': {
                label: 'Carbohydrates (net)',
                quantity: 0,
                unit: 'g',
            },
            FIBTG: {
                label: 'Fiber',
                quantity: 1.8175393883500608,
                unit: 'g',
            },
            SUGAR: {
                label: 'Sugars',
                quantity: 1.4998510545750157,
                unit: 'g',
            },
            'SUGAR.added': {
                label: 'Sugars, added',
                quantity: 0,
                unit: 'g',
            },
            PROCNT: {
                label: 'Protein',
                quantity: 102.87046869951507,
                unit: 'g',
            },
            CHOLE: {
                label: 'Cholesterol',
                quantity: 353.6449301,
                unit: 'mg',
            },
            NA: {
                label: 'Sodium',
                quantity: 1369.0268193397305,
                unit: 'mg',
            },
            CA: {
                label: 'Calcium',
                quantity: 46.50017121305595,
                unit: 'mg',
            },
            MG: {
                label: 'Magnesium',
                quantity: 134.59961554925314,
                unit: 'mg',
            },
            K: {
                label: 'Potassium',
                quantity: 1627.835369517028,
                unit: 'mg',
            },
            FE: {
                label: 'Iron',
                quantity: 2.472552427403349,
                unit: 'mg',
            },
            ZN: {
                label: 'Zinc',
                quantity: 3.184115493890243,
                unit: 'mg',
            },
            P: {
                label: 'Phosphorus',
                quantity: 978.8333494710012,
                unit: 'mg',
            },
            VITA_RAE: {
                label: 'Vitamin A',
                quantity: 57.02239998950778,
                unit: 'µg',
            },
            VITC: {
                label: 'Vitamin C',
                quantity: 38.54022383350245,
                unit: 'mg',
            },
            THIA: {
                label: 'Thiamin (B1)',
                quantity: 0.4546205815570017,
                unit: 'mg',
            },
            RIBF: {
                label: 'Riboflavin (B2)',
                quantity: 0.8202060282510018,
                unit: 'mg',
            },
            NIA: {
                label: 'Niacin (B3)',
                quantity: 43.67987273724353,
                unit: 'mg',
            },
            VITB6A: {
                label: 'Vitamin B6',
                quantity: 3.730312467655003,
                unit: 'mg',
            },
            FOLDFE: {
                label: 'Folate equivalent (total)',
                quantity: 56.11785482400281,
                unit: 'µg',
            },
            FOLFD: {
                label: 'Folate (food)',
                quantity: 56.11785482400281,
                unit: 'µg',
            },
            FOLAC: {
                label: 'Folic acid',
                quantity: 0,
                unit: 'µg',
            },
            VITB12: {
                label: 'Vitamin B12',
                quantity: 0.952543977,
                unit: 'µg',
            },
            VITD: {
                label: 'Vitamin D',
                quantity: 0,
                unit: 'µg',
            },
            TOCPHA: {
                label: 'Vitamin E',
                quantity: 4.608353496625014,
                unit: 'mg',
            },
            VITK1: {
                label: 'Vitamin K',
                quantity: 105.2173959200303,
                unit: 'µg',
            },
            'Sugar.alcohol': {
                label: 'Sugar alcohol',
                quantity: 0,
                unit: 'g',
            },
            WATER: {
                label: 'Water',
                quantity: 391.96147117399715,
                unit: 'g',
            },
        },
        totalDaily: {
            ENERC_KCAL: {
                label: 'Energy',
                quantity: 54.110609139100035,
                unit: '%',
            },
            FAT: {
                label: 'Fat',
                quantity: 107.80300346246928,
                unit: '%',
            },
            FASAT: {
                label: 'Saturated',
                quantity: 55.44708309317001,
                unit: '%',
            },
            CHOCDF: {
                label: 'Carbs',
                quantity: 1.9256145786117058,
                unit: '%',
            },
            FIBTG: {
                label: 'Fiber',
                quantity: 7.270157553400242,
                unit: '%',
            },
            PROCNT: {
                label: 'Protein',
                quantity: 205.74093739903014,
                unit: '%',
            },
            CHOLE: {
                label: 'Cholesterol',
                quantity: 117.88164336666667,
                unit: '%',
            },
            NA: {
                label: 'Sodium',
                quantity: 57.04278413915544,
                unit: '%',
            },
            CA: {
                label: 'Calcium',
                quantity: 4.650017121305595,
                unit: '%',
            },
            MG: {
                label: 'Magnesium',
                quantity: 32.04752751172694,
                unit: '%',
            },
            K: {
                label: 'Potassium',
                quantity: 34.634795096106984,
                unit: '%',
            },
            FE: {
                label: 'Iron',
                quantity: 13.736402374463049,
                unit: '%',
            },
            ZN: {
                label: 'Zinc',
                quantity: 28.946504489911305,
                unit: '%',
            },
            P: {
                label: 'Phosphorus',
                quantity: 139.83333563871446,
                unit: '%',
            },
            VITA_RAE: {
                label: 'Vitamin A',
                quantity: 6.335822221056421,
                unit: '%',
            },
            VITC: {
                label: 'Vitamin C',
                quantity: 42.82247092611384,
                unit: '%',
            },
            THIA: {
                label: 'Thiamin (B1)',
                quantity: 37.88504846308348,
                unit: '%',
            },
            RIBF: {
                label: 'Riboflavin (B2)',
                quantity: 63.09277140392321,
                unit: '%',
            },
            NIA: {
                label: 'Niacin (B3)',
                quantity: 272.99920460777207,
                unit: '%',
            },
            VITB6A: {
                label: 'Vitamin B6',
                quantity: 286.94711289653867,
                unit: '%',
            },
            FOLDFE: {
                label: 'Folate equivalent (total)',
                quantity: 14.029463706000705,
                unit: '%',
            },
            VITB12: {
                label: 'Vitamin B12',
                quantity: 39.689332375,
                unit: '%',
            },
            VITD: {
                label: 'Vitamin D',
                quantity: 0,
                unit: '%',
            },
            TOCPHA: {
                label: 'Vitamin E',
                quantity: 30.722356644166762,
                unit: '%',
            },
            VITK1: {
                label: 'Vitamin K',
                quantity: 87.68116326669193,
                unit: '%',
            },
        },
        digest: [
            {
                label: 'Fat',
                tag: 'FAT',
                schemaOrgTag: 'fatContent',
                total: 70.07195225060502,
                hasRDI: true,
                daily: 107.80300346246928,
                unit: 'g',
                sub: [
                    {
                        label: 'Saturated',
                        tag: 'FASAT',
                        schemaOrgTag: 'saturatedFatContent',
                        total: 11.089416618634003,
                        hasRDI: true,
                        daily: 55.44708309317001,
                        unit: 'g',
                    },
                    {
                        label: 'Trans',
                        tag: 'FATRN',
                        schemaOrgTag: 'transFatContent',
                        total: 0.031751465900000005,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Monounsaturated',
                        tag: 'FAMS',
                        schemaOrgTag: null,
                        total: 24.14441767765251,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Polyunsaturated',
                        tag: 'FAPU',
                        schemaOrgTag: null,
                        total: 30.083229037938004,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                ],
            },
            {
                label: 'Carbs',
                tag: 'CHOCDF',
                schemaOrgTag: 'carbohydrateContent',
                total: 5.776843735835117,
                hasRDI: true,
                daily: 1.9256145786117058,
                unit: 'g',
                sub: [
                    {
                        label: 'Carbs (net)',
                        tag: 'CHOCDF.net',
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Fiber',
                        tag: 'FIBTG',
                        schemaOrgTag: 'fiberContent',
                        total: 1.8175393883500608,
                        hasRDI: true,
                        daily: 7.270157553400242,
                        unit: 'g',
                    },
                    {
                        label: 'Sugars',
                        tag: 'SUGAR',
                        schemaOrgTag: 'sugarContent',
                        total: 1.4998510545750157,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Sugars, added',
                        tag: 'SUGAR.added',
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                ],
            },
            {
                label: 'Protein',
                tag: 'PROCNT',
                schemaOrgTag: 'proteinContent',
                total: 102.87046869951507,
                hasRDI: true,
                daily: 205.74093739903014,
                unit: 'g',
            },
            {
                label: 'Cholesterol',
                tag: 'CHOLE',
                schemaOrgTag: 'cholesterolContent',
                total: 353.6449301,
                hasRDI: true,
                daily: 117.88164336666667,
                unit: 'mg',
            },
            {
                label: 'Sodium',
                tag: 'NA',
                schemaOrgTag: 'sodiumContent',
                total: 1369.0268193397305,
                hasRDI: true,
                daily: 57.04278413915544,
                unit: 'mg',
            },
            {
                label: 'Calcium',
                tag: 'CA',
                schemaOrgTag: null,
                total: 46.50017121305595,
                hasRDI: true,
                daily: 4.650017121305595,
                unit: 'mg',
            },
            {
                label: 'Magnesium',
                tag: 'MG',
                schemaOrgTag: null,
                total: 134.59961554925314,
                hasRDI: true,
                daily: 32.04752751172694,
                unit: 'mg',
            },
            {
                label: 'Potassium',
                tag: 'K',
                schemaOrgTag: null,
                total: 1627.835369517028,
                hasRDI: true,
                daily: 34.634795096106984,
                unit: 'mg',
            },
            {
                label: 'Iron',
                tag: 'FE',
                schemaOrgTag: null,
                total: 2.472552427403349,
                hasRDI: true,
                daily: 13.736402374463049,
                unit: 'mg',
            },
            {
                label: 'Zinc',
                tag: 'ZN',
                schemaOrgTag: null,
                total: 3.184115493890243,
                hasRDI: true,
                daily: 28.946504489911305,
                unit: 'mg',
            },
            {
                label: 'Phosphorus',
                tag: 'P',
                schemaOrgTag: null,
                total: 978.8333494710012,
                hasRDI: true,
                daily: 139.83333563871446,
                unit: 'mg',
            },
            {
                label: 'Vitamin A',
                tag: 'VITA_RAE',
                schemaOrgTag: null,
                total: 57.02239998950778,
                hasRDI: true,
                daily: 6.335822221056421,
                unit: 'µg',
            },
            {
                label: 'Vitamin C',
                tag: 'VITC',
                schemaOrgTag: null,
                total: 38.54022383350245,
                hasRDI: true,
                daily: 42.82247092611384,
                unit: 'mg',
            },
            {
                label: 'Thiamin (B1)',
                tag: 'THIA',
                schemaOrgTag: null,
                total: 0.4546205815570017,
                hasRDI: true,
                daily: 37.88504846308348,
                unit: 'mg',
            },
            {
                label: 'Riboflavin (B2)',
                tag: 'RIBF',
                schemaOrgTag: null,
                total: 0.8202060282510018,
                hasRDI: true,
                daily: 63.09277140392321,
                unit: 'mg',
            },
            {
                label: 'Niacin (B3)',
                tag: 'NIA',
                schemaOrgTag: null,
                total: 43.67987273724353,
                hasRDI: true,
                daily: 272.99920460777207,
                unit: 'mg',
            },
            {
                label: 'Vitamin B6',
                tag: 'VITB6A',
                schemaOrgTag: null,
                total: 3.730312467655003,
                hasRDI: true,
                daily: 286.94711289653867,
                unit: 'mg',
            },
            {
                label: 'Folate equivalent (total)',
                tag: 'FOLDFE',
                schemaOrgTag: null,
                total: 56.11785482400281,
                hasRDI: true,
                daily: 14.029463706000705,
                unit: 'µg',
            },
            {
                label: 'Folate (food)',
                tag: 'FOLFD',
                schemaOrgTag: null,
                total: 56.11785482400281,
                hasRDI: false,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Folic acid',
                tag: 'FOLAC',
                schemaOrgTag: null,
                total: 0,
                hasRDI: false,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Vitamin B12',
                tag: 'VITB12',
                schemaOrgTag: null,
                total: 0.952543977,
                hasRDI: true,
                daily: 39.689332375,
                unit: 'µg',
            },
            {
                label: 'Vitamin D',
                tag: 'VITD',
                schemaOrgTag: null,
                total: 0,
                hasRDI: true,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Vitamin E',
                tag: 'TOCPHA',
                schemaOrgTag: null,
                total: 4.608353496625014,
                hasRDI: true,
                daily: 30.722356644166762,
                unit: 'mg',
            },
            {
                label: 'Vitamin K',
                tag: 'VITK1',
                schemaOrgTag: null,
                total: 105.2173959200303,
                hasRDI: true,
                daily: 87.68116326669193,
                unit: 'µg',
            },
            {
                label: 'Sugar alcohols',
                tag: 'Sugar.alcohol',
                schemaOrgTag: null,
                total: 0,
                hasRDI: false,
                daily: 0,
                unit: 'g',
            },
            {
                label: 'Water',
                tag: 'WATER',
                schemaOrgTag: null,
                total: 391.96147117399715,
                hasRDI: false,
                daily: 0,
                unit: 'g',
            },
        ],
    },
    {
        uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_dd4a76ee9f4ce2efd21e40e3d620f8c4',
        label: 'Steak & Chips Salad',
        image: 'https://www.edamam.com/web-img/72e/72ebeef4f13b029165ce5fc4a675130e.jpg',
        images: {
            THUMBNAIL: {
                url: 'https://www.edamam.com/web-img/72e/72ebeef4f13b029165ce5fc4a675130e-s.jpg',
                width: 100,
                height: 100,
            },
            SMALL: {
                url: 'https://www.edamam.com/web-img/72e/72ebeef4f13b029165ce5fc4a675130e-m.jpg',
                width: 200,
                height: 200,
            },
            REGULAR: {
                url: 'https://www.edamam.com/web-img/72e/72ebeef4f13b029165ce5fc4a675130e.jpg',
                width: 300,
                height: 300,
            },
            LARGE: {
                url: 'https://www.edamam.com/web-img/72e/72ebeef4f13b029165ce5fc4a675130e-l.jpg',
                width: 600,
                height: 600,
            },
        },
        source: 'BBC Good Food',
        url: 'http://www.bbcgoodfood.com/recipes/3076/',
        shareAs:
            'http://www.edamam.com/recipe/steak-chips-salad-dd4a76ee9f4ce2efd21e40e3d620f8c4/salad',
        yield: 4,
        dietLabels: ['High-Fiber'],
        healthLabels: [
            'Dairy-Free',
            'Gluten-Free',
            'Wheat-Free',
            'Egg-Free',
            'Peanut-Free',
            'Tree-Nut-Free',
            'Soy-Free',
            'Fish-Free',
            'Shellfish-Free',
            'Pork-Free',
            'Crustacean-Free',
            'Celery-Free',
            'Sesame-Free',
            'Lupine-Free',
            'Mollusk-Free',
            'Alcohol-Free',
        ],
        cautions: [],
        ingredientLines: [
            '750.0g bag frozen potato wedges',
            '1.0 tbsp olive oil',
            '2 pieces sirloin steak , about 350g/12oz in total',
            '120.0g bag herb salad',
            '6.0 tbsp honey and mustard salad dessing , bought or homemade',
        ],
        ingredients: [
            {
                text: '750.0g bag frozen potato wedges',
                quantity: 750,
                measure: 'gram',
                food: 'potato',
                weight: 750,
                foodCategory: 'vegetables',
                foodId: 'food_abiw5baauresjmb6xpap2bg3otzu',
                image: 'https://www.edamam.com/food-img/651/6512e82417bce15c2899630c1a2799df.jpg',
            },
            {
                text: '1.0 tbsp olive oil',
                quantity: 1,
                measure: 'tablespoon',
                food: 'olive oil',
                weight: 13.5,
                foodCategory: 'Oils',
                foodId: 'food_b1d1icuad3iktrbqby0hiagafaz7',
                image: 'https://www.edamam.com/food-img/4d6/4d651eaa8a353647746290c7a9b29d84.jpg',
            },
            {
                text: '2 pieces sirloin steak , about 350g/12oz in total',
                quantity: 2,
                measure: '<unit>',
                food: 'sirloin steak',
                weight: 680,
                foodCategory: 'meats',
                foodId: 'food_aifm62daw1i6txalya881bcetyzn',
                image: 'https://www.edamam.com/food-img/4f1/4f10105d5c8178f25590ca6dfcd37fca.jpg',
            },
            {
                text: '120.0g bag herb salad',
                quantity: 120,
                measure: 'gram',
                food: 'herb',
                weight: 120,
                foodCategory: 'Condiments and sauces',
                foodId: 'food_avsq22zadwyb5cb5sl1byaa4mbo8',
                image: 'https://www.edamam.com/food-img/89b/89b37a04e46e052671d73addcb84aa51.jpg',
            },
            {
                text: '6.0 tbsp honey and mustard salad dessing , bought or homemade',
                quantity: 6,
                measure: 'tablespoon',
                food: 'honey',
                weight: 126,
                foodCategory: null,
                foodId: 'food_bn6aoj9atkqx8fbkli859bbbxx62',
                image: 'https://www.edamam.com/food-img/198/198c7b25c23b4235b4cc33818c7b335f.jpg',
            },
            {
                text: '6.0 tbsp honey and mustard salad dessing , bought or homemade',
                quantity: 6,
                measure: 'tablespoon',
                food: 'mustard',
                weight: 93.3749999984214,
                foodCategory: 'Condiments and sauces',
                foodId: 'food_a34cdj5b0kyuhfbov30xcb50u4dv',
                image: 'https://www.edamam.com/food-img/e23/e238f2e4cfa6aa1a30f46dc73e7344eb.jpg',
            },
        ],
        calories: 2922.3049999990526,
        totalWeight: 1782.8749999984213,
        totalTime: 0,
        cuisineType: ['american'],
        mealType: ['lunch/dinner'],
        dishType: ['salad'],
        totalNutrients: {
            ENERC_KCAL: {
                label: 'Energy',
                quantity: 2922.3049999990526,
                unit: 'kcal',
            },
            FAT: {
                label: 'Fat',
                quantity: 123.31372499994727,
                unit: 'g',
            },
            FASAT: {
                label: 'Saturated',
                quantity: 44.72330249999663,
                unit: 'g',
            },
            FATRN: {
                label: 'Trans',
                quantity: 0.008403749999857926,
                unit: 'g',
            },
            FAMS: {
                label: 'Monounsaturated',
                quantity: 54.04817749996556,
                unit: 'g',
            },
            FAPU: {
                label: 'Polyunsaturated',
                quantity: 7.586227499987782,
                unit: 'g',
            },
            CHOCDF: {
                label: 'Carbs',
                quantity: 317.02076249990796,
                unit: 'g',
            },
            'CHOCDF.net': {
                label: 'Carbohydrates (net)',
                quantity: 0,
                unit: 'g',
            },
            FIBTG: {
                label: 'Fiber',
                quantity: 64.88699999993686,
                unit: 'g',
            },
            SUGAR: {
                label: 'Sugars',
                quantity: 112.23224999998548,
                unit: 'g',
            },
            'SUGAR.added': {
                label: 'Sugars, added',
                quantity: 103.47120000000001,
                unit: 'g',
            },
            PROCNT: {
                label: 'Protein',
                quantity: 165.40822499994096,
                unit: 'g',
            },
            CHOLE: {
                label: 'Cholesterol',
                quantity: 530.4,
                unit: 'mg',
            },
            NA: {
                label: 'Sodium',
                quantity: 1493.9699999825725,
                unit: 'mg',
            },
            CA: {
                label: 'Calcium',
                quantity: 2594.5212499990057,
                unit: 'mg',
            },
            MG: {
                label: 'Magnesium',
                quantity: 619.8399999992423,
                unit: 'mg',
            },
            K: {
                label: 'Potassium',
                quantity: 6443.084999997601,
                unit: 'mg',
            },
            FE: {
                label: 'Iron',
                quantity: 166.20613749997457,
                unit: 'mg',
            },
            ZN: {
                label: 'Zinc',
                quantity: 34.741799999989894,
                unit: 'mg',
            },
            P: {
                label: 'Phosphorus',
                quantity: 2005.3849999982951,
                unit: 'mg',
            },
            VITA_RAE: {
                label: 'Vitamin A',
                quantity: 232.66874999992106,
                unit: 'µg',
            },
            VITC: {
                label: 'Vitamin C',
                quantity: 208.66012499999525,
                unit: 'mg',
            },
            THIA: {
                label: 'Thiamin (B1)',
                quantity: 1.741273749997206,
                unit: 'mg',
            },
            RIBF: {
                label: 'Riboflavin (B2)',
                quantity: 1.4032424999988948,
                unit: 'mg',
            },
            NIA: {
                label: 'Niacin (B3)',
                quantity: 58.20302874999108,
                unit: 'mg',
            },
            VITB6A: {
                label: 'Vitamin B6',
                quantity: 6.612902499998896,
                unit: 'mg',
            },
            FOLDFE: {
                label: 'Folate equivalent (total)',
                quantity: 532.6562499998895,
                unit: 'µg',
            },
            FOLFD: {
                label: 'Folate (food)',
                quantity: 532.6562499998895,
                unit: 'µg',
            },
            FOLAC: {
                label: 'Folic acid',
                quantity: 0,
                unit: 'µg',
            },
            VITB12: {
                label: 'Vitamin B12',
                quantity: 7.548,
                unit: 'µg',
            },
            VITD: {
                label: 'Vitamin D',
                quantity: 0,
                unit: 'µg',
            },
            TOCPHA: {
                label: 'Vitamin E',
                quantity: 13.840399999994318,
                unit: 'mg',
            },
            VITK1: {
                label: 'Vitamin K',
                quantity: 2091.284249999978,
                unit: 'µg',
            },
            'Sugar.alcohol': {
                label: 'Sugar alcohol',
                quantity: 0,
                unit: 'g',
            },
            WATER: {
                label: 'Water',
                quantity: 1145.2335499986787,
                unit: 'g',
            },
        },
        totalDaily: {
            ENERC_KCAL: {
                label: 'Energy',
                quantity: 146.11524999995262,
                unit: '%',
            },
            FAT: {
                label: 'Fat',
                quantity: 189.71342307684193,
                unit: '%',
            },
            FASAT: {
                label: 'Saturated',
                quantity: 223.61651249998312,
                unit: '%',
            },
            CHOCDF: {
                label: 'Carbs',
                quantity: 105.67358749996932,
                unit: '%',
            },
            FIBTG: {
                label: 'Fiber',
                quantity: 259.54799999974745,
                unit: '%',
            },
            PROCNT: {
                label: 'Protein',
                quantity: 330.81644999988185,
                unit: '%',
            },
            CHOLE: {
                label: 'Cholesterol',
                quantity: 176.8,
                unit: '%',
            },
            NA: {
                label: 'Sodium',
                quantity: 62.24874999927386,
                unit: '%',
            },
            CA: {
                label: 'Calcium',
                quantity: 259.4521249999006,
                unit: '%',
            },
            MG: {
                label: 'Magnesium',
                quantity: 147.58095238077198,
                unit: '%',
            },
            K: {
                label: 'Potassium',
                quantity: 137.08691489356596,
                unit: '%',
            },
            FE: {
                label: 'Iron',
                quantity: 923.3674305554143,
                unit: '%',
            },
            ZN: {
                label: 'Zinc',
                quantity: 315.8345454544536,
                unit: '%',
            },
            P: {
                label: 'Phosphorus',
                quantity: 286.4835714283279,
                unit: '%',
            },
            VITA_RAE: {
                label: 'Vitamin A',
                quantity: 25.85208333332456,
                unit: '%',
            },
            VITC: {
                label: 'Vitamin C',
                quantity: 231.84458333332805,
                unit: '%',
            },
            THIA: {
                label: 'Thiamin (B1)',
                quantity: 145.1061458331005,
                unit: '%',
            },
            RIBF: {
                label: 'Riboflavin (B2)',
                quantity: 107.94173076914575,
                unit: '%',
            },
            NIA: {
                label: 'Niacin (B3)',
                quantity: 363.76892968744426,
                unit: '%',
            },
            VITB6A: {
                label: 'Vitamin B6',
                quantity: 508.6848076922227,
                unit: '%',
            },
            FOLDFE: {
                label: 'Folate equivalent (total)',
                quantity: 133.16406249997237,
                unit: '%',
            },
            VITB12: {
                label: 'Vitamin B12',
                quantity: 314.5,
                unit: '%',
            },
            VITD: {
                label: 'Vitamin D',
                quantity: 0,
                unit: '%',
            },
            TOCPHA: {
                label: 'Vitamin E',
                quantity: 92.26933333329545,
                unit: '%',
            },
            VITK1: {
                label: 'Vitamin K',
                quantity: 1742.7368749999814,
                unit: '%',
            },
        },
        digest: [
            {
                label: 'Fat',
                tag: 'FAT',
                schemaOrgTag: 'fatContent',
                total: 123.31372499994727,
                hasRDI: true,
                daily: 189.71342307684193,
                unit: 'g',
                sub: [
                    {
                        label: 'Saturated',
                        tag: 'FASAT',
                        schemaOrgTag: 'saturatedFatContent',
                        total: 44.72330249999663,
                        hasRDI: true,
                        daily: 223.61651249998312,
                        unit: 'g',
                    },
                    {
                        label: 'Trans',
                        tag: 'FATRN',
                        schemaOrgTag: 'transFatContent',
                        total: 0.008403749999857926,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Monounsaturated',
                        tag: 'FAMS',
                        schemaOrgTag: null,
                        total: 54.04817749996556,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Polyunsaturated',
                        tag: 'FAPU',
                        schemaOrgTag: null,
                        total: 7.586227499987782,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                ],
            },
            {
                label: 'Carbs',
                tag: 'CHOCDF',
                schemaOrgTag: 'carbohydrateContent',
                total: 317.02076249990796,
                hasRDI: true,
                daily: 105.67358749996932,
                unit: 'g',
                sub: [
                    {
                        label: 'Carbs (net)',
                        tag: 'CHOCDF.net',
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Fiber',
                        tag: 'FIBTG',
                        schemaOrgTag: 'fiberContent',
                        total: 64.88699999993686,
                        hasRDI: true,
                        daily: 259.54799999974745,
                        unit: 'g',
                    },
                    {
                        label: 'Sugars',
                        tag: 'SUGAR',
                        schemaOrgTag: 'sugarContent',
                        total: 112.23224999998548,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Sugars, added',
                        tag: 'SUGAR.added',
                        schemaOrgTag: null,
                        total: 103.47120000000001,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                ],
            },
            {
                label: 'Protein',
                tag: 'PROCNT',
                schemaOrgTag: 'proteinContent',
                total: 165.40822499994096,
                hasRDI: true,
                daily: 330.81644999988185,
                unit: 'g',
            },
            {
                label: 'Cholesterol',
                tag: 'CHOLE',
                schemaOrgTag: 'cholesterolContent',
                total: 530.4,
                hasRDI: true,
                daily: 176.8,
                unit: 'mg',
            },
            {
                label: 'Sodium',
                tag: 'NA',
                schemaOrgTag: 'sodiumContent',
                total: 1493.9699999825725,
                hasRDI: true,
                daily: 62.24874999927386,
                unit: 'mg',
            },
            {
                label: 'Calcium',
                tag: 'CA',
                schemaOrgTag: null,
                total: 2594.5212499990057,
                hasRDI: true,
                daily: 259.4521249999006,
                unit: 'mg',
            },
            {
                label: 'Magnesium',
                tag: 'MG',
                schemaOrgTag: null,
                total: 619.8399999992423,
                hasRDI: true,
                daily: 147.58095238077198,
                unit: 'mg',
            },
            {
                label: 'Potassium',
                tag: 'K',
                schemaOrgTag: null,
                total: 6443.084999997601,
                hasRDI: true,
                daily: 137.08691489356596,
                unit: 'mg',
            },
            {
                label: 'Iron',
                tag: 'FE',
                schemaOrgTag: null,
                total: 166.20613749997457,
                hasRDI: true,
                daily: 923.3674305554143,
                unit: 'mg',
            },
            {
                label: 'Zinc',
                tag: 'ZN',
                schemaOrgTag: null,
                total: 34.741799999989894,
                hasRDI: true,
                daily: 315.8345454544536,
                unit: 'mg',
            },
            {
                label: 'Phosphorus',
                tag: 'P',
                schemaOrgTag: null,
                total: 2005.3849999982951,
                hasRDI: true,
                daily: 286.4835714283279,
                unit: 'mg',
            },
            {
                label: 'Vitamin A',
                tag: 'VITA_RAE',
                schemaOrgTag: null,
                total: 232.66874999992106,
                hasRDI: true,
                daily: 25.85208333332456,
                unit: 'µg',
            },
            {
                label: 'Vitamin C',
                tag: 'VITC',
                schemaOrgTag: null,
                total: 208.66012499999525,
                hasRDI: true,
                daily: 231.84458333332805,
                unit: 'mg',
            },
            {
                label: 'Thiamin (B1)',
                tag: 'THIA',
                schemaOrgTag: null,
                total: 1.741273749997206,
                hasRDI: true,
                daily: 145.1061458331005,
                unit: 'mg',
            },
            {
                label: 'Riboflavin (B2)',
                tag: 'RIBF',
                schemaOrgTag: null,
                total: 1.4032424999988948,
                hasRDI: true,
                daily: 107.94173076914575,
                unit: 'mg',
            },
            {
                label: 'Niacin (B3)',
                tag: 'NIA',
                schemaOrgTag: null,
                total: 58.20302874999108,
                hasRDI: true,
                daily: 363.76892968744426,
                unit: 'mg',
            },
            {
                label: 'Vitamin B6',
                tag: 'VITB6A',
                schemaOrgTag: null,
                total: 6.612902499998896,
                hasRDI: true,
                daily: 508.6848076922227,
                unit: 'mg',
            },
            {
                label: 'Folate equivalent (total)',
                tag: 'FOLDFE',
                schemaOrgTag: null,
                total: 532.6562499998895,
                hasRDI: true,
                daily: 133.16406249997237,
                unit: 'µg',
            },
            {
                label: 'Folate (food)',
                tag: 'FOLFD',
                schemaOrgTag: null,
                total: 532.6562499998895,
                hasRDI: false,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Folic acid',
                tag: 'FOLAC',
                schemaOrgTag: null,
                total: 0,
                hasRDI: false,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Vitamin B12',
                tag: 'VITB12',
                schemaOrgTag: null,
                total: 7.548,
                hasRDI: true,
                daily: 314.5,
                unit: 'µg',
            },
            {
                label: 'Vitamin D',
                tag: 'VITD',
                schemaOrgTag: null,
                total: 0,
                hasRDI: true,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Vitamin E',
                tag: 'TOCPHA',
                schemaOrgTag: null,
                total: 13.840399999994318,
                hasRDI: true,
                daily: 92.26933333329545,
                unit: 'mg',
            },
            {
                label: 'Vitamin K',
                tag: 'VITK1',
                schemaOrgTag: null,
                total: 2091.284249999978,
                hasRDI: true,
                daily: 1742.7368749999814,
                unit: 'µg',
            },
            {
                label: 'Sugar alcohols',
                tag: 'Sugar.alcohol',
                schemaOrgTag: null,
                total: 0,
                hasRDI: false,
                daily: 0,
                unit: 'g',
            },
            {
                label: 'Water',
                tag: 'WATER',
                schemaOrgTag: null,
                total: 1145.2335499986787,
                hasRDI: false,
                daily: 0,
                unit: 'g',
            },
        ],
    },
    {
        uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_227660535298bc3423969cbbbff515b6',
        label: 'Super berry smoothie',
        image: 'https://www.edamam.com/web-img/47c/47c6c839918407e63529375b48973a7b.jpg',
        images: {
            THUMBNAIL: {
                url: 'https://www.edamam.com/web-img/47c/47c6c839918407e63529375b48973a7b-s.jpg',
                width: 100,
                height: 100,
            },
            SMALL: {
                url: 'https://www.edamam.com/web-img/47c/47c6c839918407e63529375b48973a7b-m.jpg',
                width: 200,
                height: 200,
            },
            REGULAR: {
                url: 'https://www.edamam.com/web-img/47c/47c6c839918407e63529375b48973a7b.jpg',
                width: 300,
                height: 300,
            },
        },
        source: 'BBC Good Food',
        url: 'https://www.bbcgoodfood.com/recipes/super-berry-smoothie',
        shareAs:
            'http://www.edamam.com/recipe/super-berry-smoothie-227660535298bc3423969cbbbff515b6/healthy+smoothie',
        yield: 4,
        dietLabels: ['Low-Fat', 'Low-Sodium'],
        healthLabels: [
            'Vegetarian',
            'Pescatarian',
            'Gluten-Free',
            'Wheat-Free',
            'Egg-Free',
            'Peanut-Free',
            'Tree-Nut-Free',
            'Soy-Free',
            'Fish-Free',
            'Shellfish-Free',
            'Pork-Free',
            'Red-Meat-Free',
            'Crustacean-Free',
            'Celery-Free',
            'Mustard-Free',
            'Sesame-Free',
            'Lupine-Free',
            'Mollusk-Free',
            'Alcohol-Free',
            'No oil added',
            'Kosher',
        ],
        cautions: ['Gluten', 'Wheat', 'Sulfites'],
        ingredientLines: [
            '450g bag frozen berry',
            '450g pot fat-free strawberry yogurt',
            '100ml milk',
            '25g porridge oat',
            '2 tsp honey (optional)',
        ],
        ingredients: [
            {
                text: '450g bag frozen berry',
                quantity: 450,
                measure: 'gram',
                food: 'berry',
                weight: 450,
                foodCategory: 'fruit',
                foodId: 'food_bgkl0cuasoeomtbolalmcauhha54',
                image: 'https://www.edamam.com/food-img/f55/f55705a2a9ea9f7abf449a05fa968139.png',
            },
            {
                text: '450g pot fat-free strawberry yogurt',
                quantity: 450,
                measure: 'gram',
                food: 'fat-free strawberry yogurt',
                weight: 450,
                foodCategory: 'yogurt',
                foodId: 'food_b9agyaqblv1c0ra5mtktcahife4b',
                image: 'https://www.edamam.com/food-img/8dd/8dd12a31ab40047e7633f69b421c3c5f.jpg',
            },
            {
                text: '100ml milk',
                quantity: 100,
                measure: 'milliliter',
                food: 'milk',
                weight: 103.13276924062113,
                foodCategory: 'Milk',
                foodId: 'food_b49rs1kaw0jktabzkg2vvanvvsis',
                image: 'https://www.edamam.com/food-img/7c9/7c9962acf83654a8d98ea6a2ade93735.jpg',
            },
            {
                text: '25g porridge oat',
                quantity: 25,
                measure: 'gram',
                food: 'oat',
                weight: 25,
                foodCategory: null,
                foodId: 'food_akjf74ibll2id8aqb8xbha4t4axl',
                image: null,
            },
            {
                text: '2 tsp honey (optional)',
                quantity: 2,
                measure: 'teaspoon',
                food: 'honey',
                weight: 14.125000000716435,
                foodCategory: null,
                foodId: 'food_bn6aoj9atkqx8fbkli859bbbxx62',
                image: 'https://www.edamam.com/food-img/198/198c7b25c23b4235b4cc33818c7b335f.jpg',
            },
        ],
        calories: 887.1009892389568,
        totalWeight: 1042.2577692413377,
        totalTime: 10,
        cuisineType: ['american'],
        mealType: ['breakfast'],
        dishType: ['drinks'],
        totalNutrients: {
            ENERC_KCAL: {
                label: 'Energy',
                quantity: 887.1009892389568,
                unit: 'kcal',
            },
            FAT: {
                label: 'Fat',
                quantity: 7.461815000320186,
                unit: 'g',
            },
            FASAT: {
                label: 'Saturated',
                quantity: 2.8891761463375842,
                unit: 'g',
            },
            FATRN: {
                label: 'Trans',
                quantity: 0,
                unit: 'g',
            },
            FAMS: {
                label: 'Monounsaturated',
                quantity: 1.8184380862338436,
                unit: 'g',
            },
            FAPU: {
                label: 'Polyunsaturated',
                quantity: 1.5638589000192111,
                unit: 'g',
            },
            CHOCDF: {
                label: 'Carbs',
                quantity: 183.86187292414013,
                unit: 'g',
            },
            'CHOCDF.net': {
                label: 'Carbohydrates (net)',
                quantity: 0,
                unit: 'g',
            },
            FIBTG: {
                label: 'Fiber',
                quantity: 13.478250000001433,
                unit: 'g',
            },
            SUGAR: {
                label: 'Sugars',
                quantity: 147.1276548472397,
                unit: 'g',
            },
            'SUGAR.added': {
                label: 'Sugars, added',
                quantity: 11.599450000588336,
                unit: 'g',
            },
            PROCNT: {
                label: 'Protein',
                quantity: 30.64355723108172,
                unit: 'g',
            },
            CHOLE: {
                label: 'Cholesterol',
                quantity: 19.313276924062116,
                unit: 'mg',
            },
            NA: {
                label: 'Sodium',
                quantity: 310.9120907734957,
                unit: 'mg',
            },
            CA: {
                label: 'Calcium',
                quantity: 841.8875292419448,
                unit: 'mg',
            },
            MG: {
                label: 'Magnesium',
                quantity: 149.34577692407643,
                unit: 'mg',
            },
            K: {
                label: 'Potassium',
                quantity: 1470.2302553979923,
                unit: 'mg',
            },
            FE: {
                label: 'Iron',
                quantity: 2.8452648307751955,
                unit: 'mg',
            },
            ZN: {
                label: 'Zinc',
                quantity: 5.455166246191874,
                unit: 'mg',
            },
            P: {
                label: 'Phosphorus',
                quantity: 807.4465261621505,
                unit: 'mg',
            },
            VITA_RAE: {
                label: 'Vitamin A',
                quantity: 69.94107385068573,
                unit: 'µg',
            },
            VITC: {
                label: 'Vitamin C',
                quantity: 46.87062500000358,
                unit: 'mg',
            },
            THIA: {
                label: 'Thiamin (B1)',
                quantity: 0.5846910738506857,
                unit: 'mg',
            },
            RIBF: {
                label: 'Riboflavin (B2)',
                quantity: 1.2089118800169218,
                unit: 'mg',
            },
            NIA: {
                label: 'Niacin (B3)',
                quantity: 2.6801294146250196,
                unit: 'mg',
            },
            VITB6A: {
                label: 'Vitamin B6',
                quantity: 0.4842677969267955,
                unit: 'mg',
            },
            FOLDFE: {
                label: 'Folate equivalent (total)',
                quantity: 86.93913846204538,
                unit: 'µg',
            },
            FOLFD: {
                label: 'Folate (food)',
                quantity: 86.93913846204538,
                unit: 'µg',
            },
            FOLAC: {
                label: 'Folic acid',
                quantity: 0,
                unit: 'µg',
            },
            VITB12: {
                label: 'Vitamin B12',
                quantity: 2.579097461582795,
                unit: 'µg',
            },
            VITD: {
                label: 'Vitamin D',
                quantity: 1.3407260001280747,
                unit: 'µg',
            },
            TOCPHA: {
                label: 'Vitamin E',
                quantity: 2.9071929384684347,
                unit: 'mg',
            },
            VITK1: {
                label: 'Vitamin K',
                quantity: 92.10939830772188,
                unit: 'µg',
            },
            'Sugar.alcohol': {
                label: 'Sugar alcohol',
                quantity: 0,
                unit: 'g',
            },
            WATER: {
                label: 'Water',
                quantity: 813.6062845318818,
                unit: 'g',
            },
        },
        totalDaily: {
            ENERC_KCAL: {
                label: 'Energy',
                quantity: 44.35504946194784,
                unit: '%',
            },
            FAT: {
                label: 'Fat',
                quantity: 11.47971538510798,
                unit: '%',
            },
            FASAT: {
                label: 'Saturated',
                quantity: 14.445880731687922,
                unit: '%',
            },
            CHOCDF: {
                label: 'Carbs',
                quantity: 61.28729097471337,
                unit: '%',
            },
            FIBTG: {
                label: 'Fiber',
                quantity: 53.91300000000573,
                unit: '%',
            },
            PROCNT: {
                label: 'Protein',
                quantity: 61.28711446216344,
                unit: '%',
            },
            CHOLE: {
                label: 'Cholesterol',
                quantity: 6.437758974687372,
                unit: '%',
            },
            NA: {
                label: 'Sodium',
                quantity: 12.954670448895655,
                unit: '%',
            },
            CA: {
                label: 'Calcium',
                quantity: 84.18875292419447,
                unit: '%',
            },
            MG: {
                label: 'Magnesium',
                quantity: 35.55851831525629,
                unit: '%',
            },
            K: {
                label: 'Potassium',
                quantity: 31.281494795701967,
                unit: '%',
            },
            FE: {
                label: 'Iron',
                quantity: 15.807026837639976,
                unit: '%',
            },
            ZN: {
                label: 'Zinc',
                quantity: 49.59242041992613,
                unit: '%',
            },
            P: {
                label: 'Phosphorus',
                quantity: 115.34950373745006,
                unit: '%',
            },
            VITA_RAE: {
                label: 'Vitamin A',
                quantity: 7.771230427853969,
                unit: '%',
            },
            VITC: {
                label: 'Vitamin C',
                quantity: 52.078472222226196,
                unit: '%',
            },
            THIA: {
                label: 'Thiamin (B1)',
                quantity: 48.724256154223816,
                unit: '%',
            },
            RIBF: {
                label: 'Riboflavin (B2)',
                quantity: 92.99322153976321,
                unit: '%',
            },
            NIA: {
                label: 'Niacin (B3)',
                quantity: 16.75080884140637,
                unit: '%',
            },
            VITB6A: {
                label: 'Vitamin B6',
                quantity: 37.25136899436889,
                unit: '%',
            },
            FOLDFE: {
                label: 'Folate equivalent (total)',
                quantity: 21.734784615511344,
                unit: '%',
            },
            VITB12: {
                label: 'Vitamin B12',
                quantity: 107.46239423261648,
                unit: '%',
            },
            VITD: {
                label: 'Vitamin D',
                quantity: 8.938173334187164,
                unit: '%',
            },
            TOCPHA: {
                label: 'Vitamin E',
                quantity: 19.38128625645623,
                unit: '%',
            },
            VITK1: {
                label: 'Vitamin K',
                quantity: 76.75783192310156,
                unit: '%',
            },
        },
        digest: [
            {
                label: 'Fat',
                tag: 'FAT',
                schemaOrgTag: 'fatContent',
                total: 7.461815000320186,
                hasRDI: true,
                daily: 11.47971538510798,
                unit: 'g',
                sub: [
                    {
                        label: 'Saturated',
                        tag: 'FASAT',
                        schemaOrgTag: 'saturatedFatContent',
                        total: 2.8891761463375842,
                        hasRDI: true,
                        daily: 14.445880731687922,
                        unit: 'g',
                    },
                    {
                        label: 'Trans',
                        tag: 'FATRN',
                        schemaOrgTag: 'transFatContent',
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Monounsaturated',
                        tag: 'FAMS',
                        schemaOrgTag: null,
                        total: 1.8184380862338436,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Polyunsaturated',
                        tag: 'FAPU',
                        schemaOrgTag: null,
                        total: 1.5638589000192111,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                ],
            },
            {
                label: 'Carbs',
                tag: 'CHOCDF',
                schemaOrgTag: 'carbohydrateContent',
                total: 183.86187292414013,
                hasRDI: true,
                daily: 61.28729097471337,
                unit: 'g',
                sub: [
                    {
                        label: 'Carbs (net)',
                        tag: 'CHOCDF.net',
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Fiber',
                        tag: 'FIBTG',
                        schemaOrgTag: 'fiberContent',
                        total: 13.478250000001433,
                        hasRDI: true,
                        daily: 53.91300000000573,
                        unit: 'g',
                    },
                    {
                        label: 'Sugars',
                        tag: 'SUGAR',
                        schemaOrgTag: 'sugarContent',
                        total: 147.1276548472397,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Sugars, added',
                        tag: 'SUGAR.added',
                        schemaOrgTag: null,
                        total: 11.599450000588336,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                ],
            },
            {
                label: 'Protein',
                tag: 'PROCNT',
                schemaOrgTag: 'proteinContent',
                total: 30.64355723108172,
                hasRDI: true,
                daily: 61.28711446216344,
                unit: 'g',
            },
            {
                label: 'Cholesterol',
                tag: 'CHOLE',
                schemaOrgTag: 'cholesterolContent',
                total: 19.313276924062116,
                hasRDI: true,
                daily: 6.437758974687372,
                unit: 'mg',
            },
            {
                label: 'Sodium',
                tag: 'NA',
                schemaOrgTag: 'sodiumContent',
                total: 310.9120907734957,
                hasRDI: true,
                daily: 12.954670448895655,
                unit: 'mg',
            },
            {
                label: 'Calcium',
                tag: 'CA',
                schemaOrgTag: null,
                total: 841.8875292419448,
                hasRDI: true,
                daily: 84.18875292419447,
                unit: 'mg',
            },
            {
                label: 'Magnesium',
                tag: 'MG',
                schemaOrgTag: null,
                total: 149.34577692407643,
                hasRDI: true,
                daily: 35.55851831525629,
                unit: 'mg',
            },
            {
                label: 'Potassium',
                tag: 'K',
                schemaOrgTag: null,
                total: 1470.2302553979923,
                hasRDI: true,
                daily: 31.281494795701967,
                unit: 'mg',
            },
            {
                label: 'Iron',
                tag: 'FE',
                schemaOrgTag: null,
                total: 2.8452648307751955,
                hasRDI: true,
                daily: 15.807026837639976,
                unit: 'mg',
            },
            {
                label: 'Zinc',
                tag: 'ZN',
                schemaOrgTag: null,
                total: 5.455166246191874,
                hasRDI: true,
                daily: 49.59242041992613,
                unit: 'mg',
            },
            {
                label: 'Phosphorus',
                tag: 'P',
                schemaOrgTag: null,
                total: 807.4465261621505,
                hasRDI: true,
                daily: 115.34950373745006,
                unit: 'mg',
            },
            {
                label: 'Vitamin A',
                tag: 'VITA_RAE',
                schemaOrgTag: null,
                total: 69.94107385068573,
                hasRDI: true,
                daily: 7.771230427853969,
                unit: 'µg',
            },
            {
                label: 'Vitamin C',
                tag: 'VITC',
                schemaOrgTag: null,
                total: 46.87062500000358,
                hasRDI: true,
                daily: 52.078472222226196,
                unit: 'mg',
            },
            {
                label: 'Thiamin (B1)',
                tag: 'THIA',
                schemaOrgTag: null,
                total: 0.5846910738506857,
                hasRDI: true,
                daily: 48.724256154223816,
                unit: 'mg',
            },
            {
                label: 'Riboflavin (B2)',
                tag: 'RIBF',
                schemaOrgTag: null,
                total: 1.2089118800169218,
                hasRDI: true,
                daily: 92.99322153976321,
                unit: 'mg',
            },
            {
                label: 'Niacin (B3)',
                tag: 'NIA',
                schemaOrgTag: null,
                total: 2.6801294146250196,
                hasRDI: true,
                daily: 16.75080884140637,
                unit: 'mg',
            },
            {
                label: 'Vitamin B6',
                tag: 'VITB6A',
                schemaOrgTag: null,
                total: 0.4842677969267955,
                hasRDI: true,
                daily: 37.25136899436889,
                unit: 'mg',
            },
            {
                label: 'Folate equivalent (total)',
                tag: 'FOLDFE',
                schemaOrgTag: null,
                total: 86.93913846204538,
                hasRDI: true,
                daily: 21.734784615511344,
                unit: 'µg',
            },
            {
                label: 'Folate (food)',
                tag: 'FOLFD',
                schemaOrgTag: null,
                total: 86.93913846204538,
                hasRDI: false,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Folic acid',
                tag: 'FOLAC',
                schemaOrgTag: null,
                total: 0,
                hasRDI: false,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Vitamin B12',
                tag: 'VITB12',
                schemaOrgTag: null,
                total: 2.579097461582795,
                hasRDI: true,
                daily: 107.46239423261648,
                unit: 'µg',
            },
            {
                label: 'Vitamin D',
                tag: 'VITD',
                schemaOrgTag: null,
                total: 1.3407260001280747,
                hasRDI: true,
                daily: 8.938173334187164,
                unit: 'µg',
            },
            {
                label: 'Vitamin E',
                tag: 'TOCPHA',
                schemaOrgTag: null,
                total: 2.9071929384684347,
                hasRDI: true,
                daily: 19.38128625645623,
                unit: 'mg',
            },
            {
                label: 'Vitamin K',
                tag: 'VITK1',
                schemaOrgTag: null,
                total: 92.10939830772188,
                hasRDI: true,
                daily: 76.75783192310156,
                unit: 'µg',
            },
            {
                label: 'Sugar alcohols',
                tag: 'Sugar.alcohol',
                schemaOrgTag: null,
                total: 0,
                hasRDI: false,
                daily: 0,
                unit: 'g',
            },
            {
                label: 'Water',
                tag: 'WATER',
                schemaOrgTag: null,
                total: 813.6062845318818,
                hasRDI: false,
                daily: 0,
                unit: 'g',
            },
        ],
    },
    {
        uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_57e58e7a115d48787d33609d64dd040b',
        label: 'Bone builder smoothie',
        image: 'https://www.edamam.com/web-img/675/675079ba7edebe824a0d26fc45b7b921.jpg',
        images: {
            THUMBNAIL: {
                url: 'https://www.edamam.com/web-img/675/675079ba7edebe824a0d26fc45b7b921-s.jpg',
                width: 100,
                height: 100,
            },
            SMALL: {
                url: 'https://www.edamam.com/web-img/675/675079ba7edebe824a0d26fc45b7b921-m.jpg',
                width: 200,
                height: 200,
            },
            REGULAR: {
                url: 'https://www.edamam.com/web-img/675/675079ba7edebe824a0d26fc45b7b921.jpg',
                width: 300,
                height: 300,
            },
        },
        source: 'BBC Good Food',
        url: 'http://www.bbcgoodfood.com/recipes/bone-builder-smoothie',
        shareAs:
            'http://www.edamam.com/recipe/bone-builder-smoothie-57e58e7a115d48787d33609d64dd040b/healthy+smoothie',
        yield: 1,
        dietLabels: ['High-Fiber'],
        healthLabels: [
            'Vegan',
            'Vegetarian',
            'Pescatarian',
            'Paleo',
            'Mediterranean',
            'Dairy-Free',
            'Gluten-Free',
            'Wheat-Free',
            'Egg-Free',
            'Peanut-Free',
            'Tree-Nut-Free',
            'Soy-Free',
            'Fish-Free',
            'Shellfish-Free',
            'Pork-Free',
            'Red-Meat-Free',
            'Crustacean-Free',
            'Celery-Free',
            'Mustard-Free',
            'Sesame-Free',
            'Lupine-Free',
            'Mollusk-Free',
            'Alcohol-Free',
            'No oil added',
            'Sulfite-Free',
            'Kosher',
        ],
        cautions: ['Tree-Nuts', 'Sulfites'],
        ingredientLines: [
            '½ avocado, peeled, stoned and roughly chopped',
            'generous handful spinach',
            'generous handful kale, washed well',
            '50g pineapple chunks',
            '10cm piece cucumber, roughly chopped',
            '300ml coconut water',
        ],
        ingredients: [
            {
                text: '½ avocado, peeled, stoned and roughly chopped',
                quantity: 0.5,
                measure: '<unit>',
                food: 'avocado',
                weight: 100.5,
                foodCategory: 'fruit',
                foodId: 'food_b0yuze4b1g3afpanijno5abtiu28',
                image: 'https://www.edamam.com/food-img/984/984a707ea8e9c6bf5f6498970a9e6d9d.jpg',
            },
            {
                text: 'generous handful spinach',
                quantity: 1,
                measure: 'handful',
                food: 'spinach',
                weight: 3.7500000000000004,
                foodCategory: 'vegetables',
                foodId: 'food_aoceuc6bshdej1bbsdammbnj6l6o',
                image: 'https://www.edamam.com/food-img/e6e/e6e4be375c4554ce01c8ea75232efaa6.jpg',
            },
            {
                text: 'generous handful kale, washed well',
                quantity: 1,
                measure: 'handful',
                food: 'kale',
                weight: 2,
                foodCategory: 'vegetables',
                foodId: 'food_avmg2xfbv1p91yavoxjg7bddvfaz',
                image: 'https://www.edamam.com/food-img/8e9/8e9c5417fa012e5ca068fddc5f8d3d6c.jpg',
            },
            {
                text: '50g pineapple chunks',
                quantity: 50,
                measure: 'gram',
                food: 'pineapple',
                weight: 50,
                foodCategory: 'fruit',
                foodId: 'food_b5maw38amr54vpat8d5vhbgmqfxn',
                image: 'https://www.edamam.com/food-img/2da/2da6f2397ab64ed185c082edebc4dd7c.jpg',
            },
            {
                text: '10cm piece cucumber, roughly chopped',
                quantity: 1,
                measure: '<unit>',
                food: 'cucumber',
                weight: 301,
                foodCategory: 'vegetables',
                foodId: 'food_bv7aggjag9rxsaatklqzobca5fzn',
                image: 'https://www.edamam.com/food-img/501/5015da0e5fc2b384696b3d949aefef86.jpg',
            },
            {
                text: '300ml coconut water',
                quantity: 300,
                measure: 'milliliter',
                food: 'coconut water',
                weight: 304.326204316587,
                foodCategory: 'non-dairy beverages',
                foodId: 'food_bpymsqeb489r3ubp3rysrb182jou',
                image: 'https://www.edamam.com/food-img/e87/e8727217b99560851490c217b9a2117c.jpg',
            },
        ],
        calories: 290.61447882015153,
        totalWeight: 761.576204316587,
        totalTime: 5,
        cuisineType: ['american'],
        mealType: ['breakfast'],
        dishType: ['drinks'],
        totalNutrients: {
            ENERC_KCAL: {
                label: 'Energy',
                quantity: 290.61447882015153,
                unit: 'kcal',
            },
            FAT: {
                label: 'Fat',
                quantity: 15.766277408633176,
                unit: 'g',
            },
            FASAT: {
                label: 'Saturated',
                quantity: 2.7922966195971934,
                unit: 'g',
            },
            FATRN: {
                label: 'Trans',
                quantity: 0,
                unit: 'g',
            },
            FAMS: {
                label: 'Monounsaturated',
                quantity: 9.89530609634533,
                unit: 'g',
            },
            FAPU: {
                label: 'Polyunsaturated',
                quantity: 1.960434024086332,
                unit: 'g',
            },
            CHOCDF: {
                label: 'Carbs',
                quantity: 37.66057718014538,
                unit: 'g',
            },
            'CHOCDF.net': {
                label: 'Carbohydrates (net)',
                quantity: 0,
                unit: 'g',
            },
            FIBTG: {
                label: 'Fiber',
                quantity: 12.44058824748246,
                unit: 'g',
            },
            SUGAR: {
                label: 'Sugars',
                quantity: 18.61886393266292,
                unit: 'g',
            },
            'SUGAR.added': {
                label: 'Sugars, added',
                quantity: 0,
                unit: 'g',
            },
            PROCNT: {
                label: 'Protein',
                quantity: 6.620498671079426,
                unit: 'g',
            },
            CHOLE: {
                label: 'Cholesterol',
                quantity: 0,
                unit: 'mg',
            },
            NA: {
                label: 'Sodium',
                quantity: 336.8200145324164,
                unit: 'mg',
            },
            CA: {
                label: 'Calcium',
                quantity: 146.47078903598089,
                unit: 'mg',
            },
            MG: {
                label: 'Magnesium',
                quantity: 154.25905107914676,
                unit: 'mg',
            },
            K: {
                label: 'Potassium',
                quantity: 1775.9555107914675,
                unit: 'mg',
            },
            FE: {
                label: 'Iron',
                quantity: 2.5541209925181025,
                unit: 'mg',
            },
            ZN: {
                label: 'Zinc',
                quantity: 1.6406012043165872,
                unit: 'mg',
            },
            P: {
                label: 'Phosphorus',
                quantity: 193.04274086331742,
                unit: 'mg',
            },
            VITA_RAE: {
                label: 'Vitamin A',
                quantity: 51.1725,
                unit: 'µg',
            },
            VITC: {
                label: 'Vitamin C',
                quantity: 53.13557890359809,
                unit: 'mg',
            },
            THIA: {
                label: 'Thiamin (B1)',
                quantity: 0.2845278612949761,
                unit: 'mg',
            },
            RIBF: {
                label: 'Riboflavin (B2)',
                quantity: 0.42913343646045465,
                unit: 'mg',
            },
            NIA: {
                label: 'Niacin (B3)',
                quantity: 2.5822809634532695,
                unit: 'mg',
            },
            VITB6A: {
                label: 'Vitamin B6',
                quantity: 0.5448018853813079,
                unit: 'mg',
            },
            FOLDFE: {
                label: 'Folate equivalent (total)',
                quantity: 130.69978612949762,
                unit: 'µg',
            },
            FOLFD: {
                label: 'Folate (food)',
                quantity: 130.69978612949762,
                unit: 'µg',
            },
            FOLAC: {
                label: 'Folic acid',
                quantity: 0,
                unit: 'µg',
            },
            VITB12: {
                label: 'Vitamin B12',
                quantity: 0,
                unit: 'µg',
            },
            VITD: {
                label: 'Vitamin D',
                quantity: 0,
                unit: 'µg',
            },
            TOCPHA: {
                label: 'Vitamin E',
                quantity: 2.2875750000000004,
                unit: 'mg',
            },
            VITK1: {
                label: 'Vitamin K',
                quantity: 103.02375,
                unit: 'µg',
            },
            'Sugar.alcohol': {
                label: 'Sugar alcohol',
                quantity: 0,
                unit: 'g',
            },
            WATER: {
                label: 'Water',
                quantity: 697.426211480326,
                unit: 'g',
            },
        },
        totalDaily: {
            ENERC_KCAL: {
                label: 'Energy',
                quantity: 14.530723941007576,
                unit: '%',
            },
            FAT: {
                label: 'Fat',
                quantity: 24.255811397897194,
                unit: '%',
            },
            FASAT: {
                label: 'Saturated',
                quantity: 13.961483097985967,
                unit: '%',
            },
            CHOCDF: {
                label: 'Carbs',
                quantity: 12.553525726715128,
                unit: '%',
            },
            FIBTG: {
                label: 'Fiber',
                quantity: 49.76235298992984,
                unit: '%',
            },
            PROCNT: {
                label: 'Protein',
                quantity: 13.240997342158852,
                unit: '%',
            },
            CHOLE: {
                label: 'Cholesterol',
                quantity: 0,
                unit: '%',
            },
            NA: {
                label: 'Sodium',
                quantity: 14.034167272184016,
                unit: '%',
            },
            CA: {
                label: 'Calcium',
                quantity: 14.64707890359809,
                unit: '%',
            },
            MG: {
                label: 'Magnesium',
                quantity: 36.728345495034944,
                unit: '%',
            },
            K: {
                label: 'Potassium',
                quantity: 37.78628746364824,
                unit: '%',
            },
            FE: {
                label: 'Iron',
                quantity: 14.189561069545015,
                unit: '%',
            },
            ZN: {
                label: 'Zinc',
                quantity: 14.914556402878066,
                unit: '%',
            },
            P: {
                label: 'Phosphorus',
                quantity: 27.577534409045345,
                unit: '%',
            },
            VITA_RAE: {
                label: 'Vitamin A',
                quantity: 5.685833333333333,
                unit: '%',
            },
            VITC: {
                label: 'Vitamin C',
                quantity: 59.03953211510899,
                unit: '%',
            },
            THIA: {
                label: 'Thiamin (B1)',
                quantity: 23.710655107914675,
                unit: '%',
            },
            RIBF: {
                label: 'Riboflavin (B2)',
                quantity: 33.01026434311189,
                unit: '%',
            },
            NIA: {
                label: 'Niacin (B3)',
                quantity: 16.139256021582934,
                unit: '%',
            },
            VITB6A: {
                label: 'Vitamin B6',
                quantity: 41.907837337023686,
                unit: '%',
            },
            FOLDFE: {
                label: 'Folate equivalent (total)',
                quantity: 32.674946532374406,
                unit: '%',
            },
            VITB12: {
                label: 'Vitamin B12',
                quantity: 0,
                unit: '%',
            },
            VITD: {
                label: 'Vitamin D',
                quantity: 0,
                unit: '%',
            },
            TOCPHA: {
                label: 'Vitamin E',
                quantity: 15.250500000000004,
                unit: '%',
            },
            VITK1: {
                label: 'Vitamin K',
                quantity: 85.853125,
                unit: '%',
            },
        },
        digest: [
            {
                label: 'Fat',
                tag: 'FAT',
                schemaOrgTag: 'fatContent',
                total: 15.766277408633176,
                hasRDI: true,
                daily: 24.255811397897194,
                unit: 'g',
                sub: [
                    {
                        label: 'Saturated',
                        tag: 'FASAT',
                        schemaOrgTag: 'saturatedFatContent',
                        total: 2.7922966195971934,
                        hasRDI: true,
                        daily: 13.961483097985967,
                        unit: 'g',
                    },
                    {
                        label: 'Trans',
                        tag: 'FATRN',
                        schemaOrgTag: 'transFatContent',
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Monounsaturated',
                        tag: 'FAMS',
                        schemaOrgTag: null,
                        total: 9.89530609634533,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Polyunsaturated',
                        tag: 'FAPU',
                        schemaOrgTag: null,
                        total: 1.960434024086332,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                ],
            },
            {
                label: 'Carbs',
                tag: 'CHOCDF',
                schemaOrgTag: 'carbohydrateContent',
                total: 37.66057718014538,
                hasRDI: true,
                daily: 12.553525726715128,
                unit: 'g',
                sub: [
                    {
                        label: 'Carbs (net)',
                        tag: 'CHOCDF.net',
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Fiber',
                        tag: 'FIBTG',
                        schemaOrgTag: 'fiberContent',
                        total: 12.44058824748246,
                        hasRDI: true,
                        daily: 49.76235298992984,
                        unit: 'g',
                    },
                    {
                        label: 'Sugars',
                        tag: 'SUGAR',
                        schemaOrgTag: 'sugarContent',
                        total: 18.61886393266292,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                    {
                        label: 'Sugars, added',
                        tag: 'SUGAR.added',
                        schemaOrgTag: null,
                        total: 0,
                        hasRDI: false,
                        daily: 0,
                        unit: 'g',
                    },
                ],
            },
            {
                label: 'Protein',
                tag: 'PROCNT',
                schemaOrgTag: 'proteinContent',
                total: 6.620498671079426,
                hasRDI: true,
                daily: 13.240997342158852,
                unit: 'g',
            },
            {
                label: 'Cholesterol',
                tag: 'CHOLE',
                schemaOrgTag: 'cholesterolContent',
                total: 0,
                hasRDI: true,
                daily: 0,
                unit: 'mg',
            },
            {
                label: 'Sodium',
                tag: 'NA',
                schemaOrgTag: 'sodiumContent',
                total: 336.8200145324164,
                hasRDI: true,
                daily: 14.034167272184016,
                unit: 'mg',
            },
            {
                label: 'Calcium',
                tag: 'CA',
                schemaOrgTag: null,
                total: 146.47078903598089,
                hasRDI: true,
                daily: 14.64707890359809,
                unit: 'mg',
            },
            {
                label: 'Magnesium',
                tag: 'MG',
                schemaOrgTag: null,
                total: 154.25905107914676,
                hasRDI: true,
                daily: 36.728345495034944,
                unit: 'mg',
            },
            {
                label: 'Potassium',
                tag: 'K',
                schemaOrgTag: null,
                total: 1775.9555107914675,
                hasRDI: true,
                daily: 37.78628746364824,
                unit: 'mg',
            },
            {
                label: 'Iron',
                tag: 'FE',
                schemaOrgTag: null,
                total: 2.5541209925181025,
                hasRDI: true,
                daily: 14.189561069545015,
                unit: 'mg',
            },
            {
                label: 'Zinc',
                tag: 'ZN',
                schemaOrgTag: null,
                total: 1.6406012043165872,
                hasRDI: true,
                daily: 14.914556402878066,
                unit: 'mg',
            },
            {
                label: 'Phosphorus',
                tag: 'P',
                schemaOrgTag: null,
                total: 193.04274086331742,
                hasRDI: true,
                daily: 27.577534409045345,
                unit: 'mg',
            },
            {
                label: 'Vitamin A',
                tag: 'VITA_RAE',
                schemaOrgTag: null,
                total: 51.1725,
                hasRDI: true,
                daily: 5.685833333333333,
                unit: 'µg',
            },
            {
                label: 'Vitamin C',
                tag: 'VITC',
                schemaOrgTag: null,
                total: 53.13557890359809,
                hasRDI: true,
                daily: 59.03953211510899,
                unit: 'mg',
            },
            {
                label: 'Thiamin (B1)',
                tag: 'THIA',
                schemaOrgTag: null,
                total: 0.2845278612949761,
                hasRDI: true,
                daily: 23.710655107914675,
                unit: 'mg',
            },
            {
                label: 'Riboflavin (B2)',
                tag: 'RIBF',
                schemaOrgTag: null,
                total: 0.42913343646045465,
                hasRDI: true,
                daily: 33.01026434311189,
                unit: 'mg',
            },
            {
                label: 'Niacin (B3)',
                tag: 'NIA',
                schemaOrgTag: null,
                total: 2.5822809634532695,
                hasRDI: true,
                daily: 16.139256021582934,
                unit: 'mg',
            },
            {
                label: 'Vitamin B6',
                tag: 'VITB6A',
                schemaOrgTag: null,
                total: 0.5448018853813079,
                hasRDI: true,
                daily: 41.907837337023686,
                unit: 'mg',
            },
            {
                label: 'Folate equivalent (total)',
                tag: 'FOLDFE',
                schemaOrgTag: null,
                total: 130.69978612949762,
                hasRDI: true,
                daily: 32.674946532374406,
                unit: 'µg',
            },
            {
                label: 'Folate (food)',
                tag: 'FOLFD',
                schemaOrgTag: null,
                total: 130.69978612949762,
                hasRDI: false,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Folic acid',
                tag: 'FOLAC',
                schemaOrgTag: null,
                total: 0,
                hasRDI: false,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Vitamin B12',
                tag: 'VITB12',
                schemaOrgTag: null,
                total: 0,
                hasRDI: true,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Vitamin D',
                tag: 'VITD',
                schemaOrgTag: null,
                total: 0,
                hasRDI: true,
                daily: 0,
                unit: 'µg',
            },
            {
                label: 'Vitamin E',
                tag: 'TOCPHA',
                schemaOrgTag: null,
                total: 2.2875750000000004,
                hasRDI: true,
                daily: 15.250500000000004,
                unit: 'mg',
            },
            {
                label: 'Vitamin K',
                tag: 'VITK1',
                schemaOrgTag: null,
                total: 103.02375,
                hasRDI: true,
                daily: 85.853125,
                unit: 'µg',
            },
            {
                label: 'Sugar alcohols',
                tag: 'Sugar.alcohol',
                schemaOrgTag: null,
                total: 0,
                hasRDI: false,
                daily: 0,
                unit: 'g',
            },
            {
                label: 'Water',
                tag: 'WATER',
                schemaOrgTag: null,
                total: 697.426211480326,
                hasRDI: false,
                daily: 0,
                unit: 'g',
            },
        ],
    },
]
